


# GET http://localhost:4004/odata/v4/BookStoreService/Books

# POST http://localhost:4004/odata/v4/BookStoreService/Books
# Content-Type: application/json





### GET all books
GET http://localhost:4004/odata/v4/BookStoreService/Books
 
### GET a specific book by ID
GET http://localhost:4004/odata/v4/BookStoreService/Books(ID='1')
 
### GET all authors
GET http://localhost:4004/odata/v4/BookStoreService/Authors
 
### GET a specific author by ID
GET http://localhost:4004/odata/v4/BookStoreService/Authors(ID='1')
 
### GET all reviews
GET http://localhost:4004/odata/v4/CustomerService/Reviews
 
### GET a specific review by ID
GET http://localhost:4004/odata/v4/CustomerService/Reviews(ID='1')
 
### GET books with reviews ------------------------------------------------ not implemented in my project
# GET http://localhost:4004/odata/v4/BookStoreService/BooksWithReviews          

### GET a specific book with reviews by book ID ------------------------------------------------ not implemented in my project
# GET http://localhost:4004/odata/v4/BookStoreService/BooksWithReviews(ID='1')
 
### POST a new book
POST http://localhost:4004/odata/v4/BookStoreService/Books
Content-Type: application/json
 
{
    "title": "New Book",
    "isbn": "123456789012",
    "amount_code": "INR",
    "createdAt": "2025-05-09T11:45:23",
    "createdBy": "User1",
    "modifiedAt": "2025-05-09T11:45:23",
    "modifiedBy": "User1"
}
 
### POST a new author
POST http://localhost:4004/odata/v4/BookStoreService/Authors
Content-Type: application/json
 
{
    "authorName": "New Author",
    "isbn": "123456789012",
    "address_address": "123 New St",
    "address_pincode": 12345
}
 
### POST a new review
POST http://localhost:4004/odata/v4/CustomerService/Reviews
Content-Type: application/json
 
{
    "rating": 5,
    "comment": "Excellent book!",
    "book_ID": "1"
}